# Use container-based infrastructure
sudo: false

# https://dzone.com/articles/speed-up-gradle-build-on-travisci
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
 - $HOME/.gradle/nodejs/
 - node_modules

language: java

jdk:
- oraclejdk8

# https://dzone.com/articles/speed-up-gradle-build-on-travisci
install: echo "skip 'gradle assemble' step"

script:
- ./scripts/travis-build.sh
- ./scripts/travis-deploy.sh
